version: '3.7'

services:
  test_cast_db:
      image: postgres:12.1-alpine
      container_name: '${APP_NAME}_cast_test_db'
      ports:
        - "5433:5432"
      volumes:
        - postgres_data_test_cast:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=${DB_CAST_USER}
        - POSTGRES_PASSWORD=${DB_CAST_PASS}
        - POSTGRES_DB=${DB_CAST}

  test_movie_db:
    image: postgres:12.1-alpine
    container_name: '${APP_NAME}_movie_test_db'
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_test_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_MOVIE_USER}
      - POSTGRES_PASSWORD=${DB_MOVIE_PASS}
      - POSTGRES_DB=${DB_MOVIE}

  test_movie_theaters_db:
    image: postgres:12.1-alpine
    container_name: '${APP_NAME}_movie_theater_test_db'
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_test_movie_theaters:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_MOVIE_THEATER_USER}
      - POSTGRES_PASSWORD=${DB_MOVIE_THEATER_PASS}
      - POSTGRES_DB=${DB_MOVIE_THEATER}

volumes:
  postgres_data_test_cast:
  postgres_data_test_movie:
  postgres_data_test_movie_theaters: